baseURL = "https://huynhcongdanh.github.io/resume/"
languageCode = "en-us"
title = "Danh Huynh | Terminal"
theme = "terminal"

[params]
  # The text that appears at the top of the "terminal"
  contentTypeName = "posts"
  placeholderPrompt = "guest@danhuynh.info:~$"
  
  # Choose your 'phosphor' color: green, blue, red, orange, pink
  themeColor = "green"

  [params.terminal]
    showTerminal = true
    userName = "danh"
    terminalPrompt = "λ"