baseURL = "https://huynhcongdanh.github.io/resume/"
languageCode = "en-us"
title = "Danh Huynh | Terminal"
theme = "terminal"

[params]
  # Important for the Terminal theme to show content on the front page
  contentTypeName = "posts"